config/routes.rb
Rails.application.routes.draw do
  
  root "welcome#index"
  devise_for :students

  resources :students
	resources :courses
	resources :semesters
	resources :activitys

end

app/views/layouts/_nav_with_student.html.erb
<a href="" class="mdl-navigation__link">Logado como <%= current_student.name %></a>
<%= link_to "Cursos", courses_path, class: "mdl-button mdl-button--light" %>
<%= link_to "Sair", destroy_student_session_path, method: :delete, class: "mdl-button mdl-button--light" %>

app/views/layouts/_nav_without_student.html.erb
<%= link_to "Entrar", new_student_session_path, class: "mdl-navigation__link" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html ng-app="EADT">
  <head>
    <title>TeacherEad</title>
    <%= csrf_meta_tags %>

    <link rel="stylesheet" href="https://code.getmdl.io/1.2.1/material.blue-orange.min.css" />
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <script defer src="https://code.getmdl.io/1.2.1/material.min.js"></script>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%= javascript_include_tag 'angular_script', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="mdl-layout mdl-js-layout mdl-layout--fixed-header" ng-controller="EADTCtrl">

    <header class="mdl-layout__header">
      <div class="mdl-layout__header-row">
        <%= link_to "EAD Teacher", root_path, class: "mdl-title not-link" %>

        <div class="mdl-layout-spacer"></div>

        <nav class="mdl-navigation mdl-layout--large-screen-only">
          <%= nav_content %>
        </nav>
      </div>
    </header>

    <div class="mdl-layout__drawer mdl-layout--small-screen-only">
      <span class="mdl-layout-title">EAD Teacher</span>

        <nav class="mdl-navigation">
          <a href="" class="mdl-navigation__link">Entrar</a>
        </nav>
    </div>

    <main class="mdl-layout__content">
      <div class="mdl-grid">
        <div class="mdl-cell mdl-cell--1-col mdl-layout--medium-screen-only"></div>
        <div class="mdl-cell mdl-cell--10-col mdl-cell--8-col-tablet mdl-cell--4-col-phone">
          <%= yield %>    
        </div>
    </div>
    </main>

  </body>
</html>